using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using POSSystemWithInventory.ConstantAndHelpers;
using POSSystemWithInventory.EntityModel;
using POSSystemWithInventory.Models;
using POSSystemWithInventory.RepositoryPattern.Interfaces.IUnitOfWork;

namespace POSSystemWithInventory.Controllers
{
    public class InventoryController : Controller
    {
        private readonly IUnitOfWork context;

        public InventoryController(IUnitOfWork unitOfWork)
        {
            context = unitOfWork;
        }

        #region Purchase Product CRUD
        public IActionResult Index()
        {
            var supplierList = context.Supplier.GetAll().ToList();
            var productList = context.Product.GetAll().ToList();
            var vatAndTax = context.VatAndTax.GetAll().ToList();

            PurchaseProductVM purchaseProduct = new PurchaseProductVM()
            {
                SupplierItem = POSHelper.Supplier(supplierList),
                ProductItem = POSHelper.Product(productList),
                VatItem = POSHelper.VatAndTax(vatAndTax),
            };
            return View(purchaseProduct);
        }
        [HttpPost]
        public IActionResult Index(PurchaseProductVM purchaseProduct)
        {
            try
            {
                #region Pushing into Purchase Product 
                PurchaseProduct purchase = new PurchaseProduct()
                {
                    InvoiceNumber = purchaseProduct.InvoiceNumber,
                    SupplierId = purchaseProduct.SupplierId,
                    SubTotal = purchaseProduct.SubTotal,
                    GrandTotal = purchaseProduct.GrandTotal,
                    Discount = purchaseProduct.Discount,
                    Dues = purchaseProduct.Dues,
                    PaidAmount = purchaseProduct.PaidAmount,
                    PaymentMode = purchaseProduct.PaymentMode,
                };
                context.PurchaseProduct.Add(purchase);
                context.Save();
                #endregion

                #region Pushing into Purchase Product Detail
                foreach (var item in purchaseProduct.PurchaseProductDetails)
                {
                    PurchaseProductDetail purchaseProductDetail = new PurchaseProductDetail()
                    {
                        PurchaseProductId = purchase.Id,
                        InvoiceNumber = item.InvoiceNumber,
                        ProductId = item.ProductId,
                        Quantity = item.Quantity,
                        UnitPrice = item.UnitPrice,
                        VatAndTaxId = item.VatAndTaxId,
                        BasePrice = item.BasePrice,
                        SellPrice = item.SellPrice,
                    };
                    context.PurchaseProductDetail.Add(purchaseProductDetail);
                    context.Save();
                    UpdateInventory(item.ProductId, item.Quantity);
                }

                #endregion

                return Json(true);
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
                throw ex;
            }
        }
        public IActionResult PurchaseListView()
        {
            return View();
        }
        #endregion

        #region Actions & Helpers 
        private void UpdateInventory(int? productId, decimal quantity)
        {
            var inventory = context.Inventory.Find(x => x.ProductId == productId).FirstOrDefault();
            if(inventory != null)
            {
                inventory.AvailableQuantity = inventory.AvailableQuantity + quantity;
                inventory.UpdatedDate = DateTime.Now.ToShortDateString();
                context.Save();
            }
            return;
        }
        private string GetInvoiceNumber()
        {
            var stockLastEntry = context.Stock.GetLastOrDefault();
            string invoiceNumber = AutoGeneratedNumber.GetStockNumber( stockLastEntry == null ? "1" : stockLastEntry.InvoiceNumber );
            return invoiceNumber;
        }
        public IActionResult InvoiceNumber()
        {
            string invoiceNumber = GetInvoiceNumber();
            return Json(invoiceNumber);
        }
        #endregion
    }
}
