using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace POSSystemWithInventory.ConstantAndHelpers
{
    public static class AutoGeneratedNumber
    {
        public static string GetInvoiceNumber(string invoiceNumber)
        {
            string prefix = "INV-";
            string number = prefix;
            int length = 6;
            string newlyGeneratedNumber = "";

            if(invoiceNumber != "1")
            {
                var splitNumber = invoiceNumber.Split("-");
                newlyGeneratedNumber = (Convert.ToInt32(splitNumber[1]) + 1).ToString();
            }
            else
            {
                newlyGeneratedNumber += "1";
            }

            for(int i = 0; i < length - newlyGeneratedNumber.Length; i++)
            {
                number += "0";
            }
            number += newlyGeneratedNumber;
            return number;
        }

        public static string GetStockNumber(string invoiceNumber)
        {
            string prefix = "PUR-";
            string number = prefix;
            int length = 6;
            string newlyGeneratedNumber = "";

            if (invoiceNumber != "1")
            {
                var splitNumber = invoiceNumber.Split("-");
                newlyGeneratedNumber = (Convert.ToInt32(splitNumber[1]) + 1).ToString();
            }
            else
            {
                newlyGeneratedNumber += "1";
            }

            for (int i = 0; i < length - newlyGeneratedNumber.Length; i++)
            {
                number += "0";
            }
            number += newlyGeneratedNumber;
            return number;
        }
    }
}
